version: "3.9"
services:
  blue:
    build: blue
    ports:
      - "8081:80"
  green:
    build: green
    ports:
      - "8082:80"
  haproxy:
    build: haproxy
    ports:
      - "8080:80"
      - "8404:8404"
    depends_on:
      - green
      - blue